services:
  postgres:
    image: postgres:16
    container_name: book_club_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: book_club_db
      POSTGRES_USER: book_club_user
      POSTGRES_PASSWORD: book_club_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
